// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `manage`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=DB_2012AFTER\MSSQLSERVER01,50002;Initial Catalog=Relief_data_dev;Persist Security Info=True;User ID=sa;Password=******;`
//     Include Views:          `True`


// -----------------------------------------------------------------------------------------
// Failed to read database schema - 無法開啟登入所要求的資料庫 "Relief_data_dev"。登入失敗。 使用者 'sa' 的登入失敗。
// -----------------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace LZAI.MgrLib.Models
{
}
