//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LZAI.Service.LZGPS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LZGPS.LZGPSDataServiceSoap")]
    public interface LZGPSDataServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRealTimeGPS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LZAI.Service.LZGPS.GetRealTimeGPSResponse GetRealTimeGPS(LZAI.Service.LZGPS.GetRealTimeGPSRequest request);
        
        // CODEGEN: 正在產生訊息合約，因為此作業具有多個傳回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRealTimeGPS", ReplyAction="*")]
        System.Threading.Tasks.Task<LZAI.Service.LZGPS.GetRealTimeGPSResponse> GetRealTimeGPSAsync(LZAI.Service.LZGPS.GetRealTimeGPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarGPS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LZAI.Service.LZGPS.GetCarGPSResponse GetCarGPS(LZAI.Service.LZGPS.GetCarGPSRequest request);
        
        // CODEGEN: 正在產生訊息合約，因為此作業具有多個傳回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarGPS", ReplyAction="*")]
        System.Threading.Tasks.Task<LZAI.Service.LZGPS.GetCarGPSResponse> GetCarGPSAsync(LZAI.Service.LZGPS.GetCarGPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ins_LZCarsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LZAI.Service.LZGPS.Ins_LZCarsListResponse Ins_LZCarsList(LZAI.Service.LZGPS.Ins_LZCarsListRequest request);
        
        // CODEGEN: 正在產生訊息合約，因為此作業具有多個傳回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ins_LZCarsList", ReplyAction="*")]
        System.Threading.Tasks.Task<LZAI.Service.LZGPS.Ins_LZCarsListResponse> Ins_LZCarsListAsync(LZAI.Service.LZGPS.Ins_LZCarsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_LZCarsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LZAI.Service.LZGPS.Del_LZCarsListResponse Del_LZCarsList(LZAI.Service.LZGPS.Del_LZCarsListRequest request);
        
        // CODEGEN: 正在產生訊息合約，因為此作業具有多個傳回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_LZCarsList", ReplyAction="*")]
        System.Threading.Tasks.Task<LZAI.Service.LZGPS.Del_LZCarsListResponse> Del_LZCarsListAsync(LZAI.Service.LZGPS.Del_LZCarsListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRealTimeGPS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRealTimeGPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mode;
        
        public GetRealTimeGPSRequest() {
        }
        
        public GetRealTimeGPSRequest(string password, string mode) {
            this.password = password;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRealTimeGPSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRealTimeGPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetRealTimeGPSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        public GetRealTimeGPSResponse() {
        }
        
        public GetRealTimeGPSResponse(string GetRealTimeGPSResult, string Message) {
            this.GetRealTimeGPSResult = GetRealTimeGPSResult;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarGPS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarGPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string plate_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string stime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string etime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string mode;
        
        public GetCarGPSRequest() {
        }
        
        public GetCarGPSRequest(string plate_no, string date, string stime, string etime, string password, string mode) {
            this.plate_no = plate_no;
            this.date = date;
            this.stime = stime;
            this.etime = etime;
            this.password = password;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCarGPSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCarGPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCarGPSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        public GetCarGPSResponse() {
        }
        
        public GetCarGPSResponse(string GetCarGPSResult, string Message) {
            this.GetCarGPSResult = GetCarGPSResult;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ins_LZCarsList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ins_LZCarsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string plate_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mode;
        
        public Ins_LZCarsListRequest() {
        }
        
        public Ins_LZCarsListRequest(string plate_no, string password, string mode) {
            this.plate_no = plate_no;
            this.password = password;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ins_LZCarsListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ins_LZCarsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Ins_LZCarsListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        public Ins_LZCarsListResponse() {
        }
        
        public Ins_LZCarsListResponse(bool Ins_LZCarsListResult, string Message) {
            this.Ins_LZCarsListResult = Ins_LZCarsListResult;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Del_LZCarsList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Del_LZCarsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string plate_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mode;
        
        public Del_LZCarsListRequest() {
        }
        
        public Del_LZCarsListRequest(string plate_no, string password, string mode) {
            this.plate_no = plate_no;
            this.password = password;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Del_LZCarsListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Del_LZCarsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Del_LZCarsListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Message;
        
        public Del_LZCarsListResponse() {
        }
        
        public Del_LZCarsListResponse(bool Del_LZCarsListResult, string Message) {
            this.Del_LZCarsListResult = Del_LZCarsListResult;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LZGPSDataServiceSoapChannel : LZAI.Service.LZGPS.LZGPSDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LZGPSDataServiceSoapClient : System.ServiceModel.ClientBase<LZAI.Service.LZGPS.LZGPSDataServiceSoap>, LZAI.Service.LZGPS.LZGPSDataServiceSoap {
        
        public LZGPSDataServiceSoapClient() {
        }
        
        public LZGPSDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LZGPSDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LZGPSDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LZGPSDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LZAI.Service.LZGPS.GetRealTimeGPSResponse LZAI.Service.LZGPS.LZGPSDataServiceSoap.GetRealTimeGPS(LZAI.Service.LZGPS.GetRealTimeGPSRequest request) {
            return base.Channel.GetRealTimeGPS(request);
        }
        
        public string GetRealTimeGPS(string password, string mode, out string Message) {
            LZAI.Service.LZGPS.GetRealTimeGPSRequest inValue = new LZAI.Service.LZGPS.GetRealTimeGPSRequest();
            inValue.password = password;
            inValue.mode = mode;
            LZAI.Service.LZGPS.GetRealTimeGPSResponse retVal = ((LZAI.Service.LZGPS.LZGPSDataServiceSoap)(this)).GetRealTimeGPS(inValue);
            Message = retVal.Message;
            return retVal.GetRealTimeGPSResult;
        }
        
        public System.Threading.Tasks.Task<LZAI.Service.LZGPS.GetRealTimeGPSResponse> GetRealTimeGPSAsync(LZAI.Service.LZGPS.GetRealTimeGPSRequest request) {
            return base.Channel.GetRealTimeGPSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LZAI.Service.LZGPS.GetCarGPSResponse LZAI.Service.LZGPS.LZGPSDataServiceSoap.GetCarGPS(LZAI.Service.LZGPS.GetCarGPSRequest request) {
            return base.Channel.GetCarGPS(request);
        }
        
        public string GetCarGPS(string plate_no, string date, string stime, string etime, string password, string mode, out string Message) {
            LZAI.Service.LZGPS.GetCarGPSRequest inValue = new LZAI.Service.LZGPS.GetCarGPSRequest();
            inValue.plate_no = plate_no;
            inValue.date = date;
            inValue.stime = stime;
            inValue.etime = etime;
            inValue.password = password;
            inValue.mode = mode;
            LZAI.Service.LZGPS.GetCarGPSResponse retVal = ((LZAI.Service.LZGPS.LZGPSDataServiceSoap)(this)).GetCarGPS(inValue);
            Message = retVal.Message;
            return retVal.GetCarGPSResult;
        }
        
        public System.Threading.Tasks.Task<LZAI.Service.LZGPS.GetCarGPSResponse> GetCarGPSAsync(LZAI.Service.LZGPS.GetCarGPSRequest request) {
            return base.Channel.GetCarGPSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LZAI.Service.LZGPS.Ins_LZCarsListResponse LZAI.Service.LZGPS.LZGPSDataServiceSoap.Ins_LZCarsList(LZAI.Service.LZGPS.Ins_LZCarsListRequest request) {
            return base.Channel.Ins_LZCarsList(request);
        }
        
        public bool Ins_LZCarsList(string plate_no, string password, string mode, out string Message) {
            LZAI.Service.LZGPS.Ins_LZCarsListRequest inValue = new LZAI.Service.LZGPS.Ins_LZCarsListRequest();
            inValue.plate_no = plate_no;
            inValue.password = password;
            inValue.mode = mode;
            LZAI.Service.LZGPS.Ins_LZCarsListResponse retVal = ((LZAI.Service.LZGPS.LZGPSDataServiceSoap)(this)).Ins_LZCarsList(inValue);
            Message = retVal.Message;
            return retVal.Ins_LZCarsListResult;
        }
        
        public System.Threading.Tasks.Task<LZAI.Service.LZGPS.Ins_LZCarsListResponse> Ins_LZCarsListAsync(LZAI.Service.LZGPS.Ins_LZCarsListRequest request) {
            return base.Channel.Ins_LZCarsListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LZAI.Service.LZGPS.Del_LZCarsListResponse LZAI.Service.LZGPS.LZGPSDataServiceSoap.Del_LZCarsList(LZAI.Service.LZGPS.Del_LZCarsListRequest request) {
            return base.Channel.Del_LZCarsList(request);
        }
        
        public bool Del_LZCarsList(string plate_no, string password, string mode, out string Message) {
            LZAI.Service.LZGPS.Del_LZCarsListRequest inValue = new LZAI.Service.LZGPS.Del_LZCarsListRequest();
            inValue.plate_no = plate_no;
            inValue.password = password;
            inValue.mode = mode;
            LZAI.Service.LZGPS.Del_LZCarsListResponse retVal = ((LZAI.Service.LZGPS.LZGPSDataServiceSoap)(this)).Del_LZCarsList(inValue);
            Message = retVal.Message;
            return retVal.Del_LZCarsListResult;
        }
        
        public System.Threading.Tasks.Task<LZAI.Service.LZGPS.Del_LZCarsListResponse> Del_LZCarsListAsync(LZAI.Service.LZGPS.Del_LZCarsListRequest request) {
            return base.Channel.Del_LZCarsListAsync(request);
        }
    }
}
